Header/Footer Commit (0927)
RealManClub/BeACE_Rank_FE pull request #5
Opened 2023-09-27 04:53 UTC by dd4u01

0927

src/common 폴더에 Header.tsx 와 Footer.tsx 작성.

프로젝트의 모든 페이지에 적용하기 위해 pages/_app.tsx 와 pages/index.tsx 를 수정해보았으나 의도대로 먹히지 않음.

정상적으로 작동하는 페이지 단에서 css를 확인하지 못했으므로 확인 후 부족한 점 피드백 부탁드립니다.

2023-10-02 14:28 UTC, HarenKei requested changes
짚어드린 부분만 수정해주시면 감사하겠습니다!

2023-10-02 14:28 UTC, HarenKei commented on pages/_app.tsx
> +    <SessionProvider session={pageProps.session}>
Session Provider는 로그인 기능 구현용인가용?

2023-10-02 14:28 UTC, HarenKei commented on src/Common/Footer.tsx
> +                <a href={'/'}>▷개인정보 처리 방침</a>
<a> 보다는 next/Link 써주시는게 좋습니다

2023-10-02 14:28 UTC, HarenKei commented on src/Common/Footer.tsx
> +                Copyright 2023. 사나이클럽. All rights reserved.
이런건 p 태그로 감싸주는게 좋을 것 같아요

2023-10-02 14:28 UTC, HarenKei commented on src/Common/Header.tsx
> +    display:flex;
flex-direction 속성으로 row인지 column인지 정해주는것도 좋을 것 같습니다~

2023-10-02 14:28 UTC, HarenKei commented on src/Common/Footer.tsx
> +    font-size: 36px;
font 단위는 추후 반응형 적용을 위해 rem, em으로 작성해주세요.
기본 1em, 1rem은 16pt이고 변환해주는 사이트도 많으니 참고해주세요

2023-10-04 05:50 UTC, dd4u01 commented on pages/_app.tsx
> +    <SessionProvider session={pageProps.session}>
next-auth로 로그인 구현한다면 그대로 사용할 것 같아서 넣어뒀습니다!

2023-10-04 11:22 UTC, merged